version: "3"

networks:
  base-api:


services:
  postgres:
    image: postgres
    restart: on-failure
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=pg_password
      - PGDATA=/var/lib/postgresql/data/pgdata
      - POSTGRES_DB=api_database
    volumes:
      - ./pgdata:/var/lib/postgresql
    ports:
      - "8420:5432"

  base_api:
    build:
      context: ./
      dockerfile: Dockerfile
    networks:
      - base-api
    volumes:
      - ./src:/home/user/base-api
    ports:
      - "3420:3000"
    depends_on:
      - postgres
